project:
  type: book
  output-dir: ../docs

book:
  title: "fdid -- User Manual"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - 01-start.Rmd
    - 02-main.Rmd
    - 03-continuous-overview.Rmd
    - 04-kernel-continuous-g.Rmd
    - 05-dml-continuous-g.Rmd
    - 06-visualization.Rmd
    - 07-sensitivity.Rmd
    - references.qmd

delete_merged_file: true

bibliography: references.bib

nocite: |
  @*

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: false
    code-tools: true
    code-link: true
    toc-depth: 3

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
